parameters:
    app.path.news_images: /images/now

vich_uploader:
    db_driver: orm

    mappings:
        news_images:
            uri_prefix: /images/now
            upload_destination: '%kernel.project_dir%/public/images/now'
