parameters:
    app.path.news_images: /images/news

vich_uploader:
    db_driver: orm

    mappings:
        news_images:
            uri_prefix: /images/news
            upload_destination: '%kernel.project_dir%/public/images/news'
